# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawelIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('instance_index', models.IntegerField()),
                ('title', models.CharField(default='', max_length=100)),
                ('rating', models.CharField(default='', max_length=100)),
                ('votes', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('website', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
