# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawelissue',
            name='crawel_number',
        ),
    ]
