# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawelissue',
            old_name='employee',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='crawelissue',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crawelissue',
            name='city_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
